version: '3.9'
services:
  postgres_db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: db_agenda
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./db/backup.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - "5432:5432"
    networks:
      - my_network

  api_service:
    build:
      context: ./demoApiAgenda
      dockerfile: Dockerfile
    container_name: api_service
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - postgres_db
    ports:
      - "9090:9090"
    networks:
      - my_network

  frontend_service:
    build:
      context: ./app-mi-agenda
      dockerfile: Dockerfile
    ports:
      - "5175:5175"
    depends_on:
      - api_service
    networks:
      - my_network

networks:
  my_network:
    driver: bridge